import { test } from '@playwright/test';
import { allerA, montee } from './aide';
test('debug', async ({ page }) => {
  await page.goto('/');
  await allerA(page, 'aether', 0.7);
  await montee(page, 'aether');
  await allerA(page, 'aether', 0.7);
  const s = page.locator('#aether');
  await s.locator('[data-pilule]').click();
  await page.keyboard.type('compare rust et zig pour un jeu');
  await page.keyboard.press('Enter');
  await page.waitForTimeout(2000);
  const z = () => s.locator('[data-toile]').evaluate((t) => getComputedStyle(t).getPropertyValue('--zoom'));
  console.log('z0', await z());
  const b = await s.locator('[data-zoom="+"]').boundingBox();
  console.log('box', b, await page.evaluate(([x, y]) => { const e = document.elementFromPoint(x, y); return e?.outerHTML.slice(0, 120); }, [b!.x + b!.width / 2, b!.y + b!.height / 2]));
  await s.locator('[data-zoom="+"]').click();
  console.log('z1', await z());
  await page.screenshot({ path: 'test-results/dbg-zoom.png' });
});
